version: '3.7'
services:
  naming-server:
    image: kmmanu/service-registry:0.0.2-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always
    networks:
      - spring-boot-test

  api-gateway-server:
    image: kmmanu/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    restart: always
    depends_on: 
      - naming-server
    networks:
      - spring-boot-test

  greeting-service:
    image: kmmanu/greeting-service:0.0.2-SNAPSHOT
    ports:
      - "8081:8081"
    restart: always
    depends_on: 
      - naming-server
    networks:
      - spring-boot-test

  greeting-client:
    image: kmmanu/greeting-client:0.0.3-SNAPSHOT
    ports:
      - "8082:8082"
    restart: always
    depends_on: 
      - greeting-service
      - naming-server
    networks:
      - spring-boot-test
  
# Networks to be created to facilitate communication between containers
networks:
  spring-boot-test: